<script type="text/javascript" src="lib/handlebars-1.0.rc.1.js"></script>
<script type="text/javascript" src="lib/jquery-1.9.0.js"></script>
<script type="text/javascript" src="lib/jquery-ui.js"></script>
<script type="text/javascript" src="lib/jquery.blockui.js"></script>
<script type="text/javascript" src="lib/jquery.dataTables.js"></script>
<script type="text/javascript" src="lib/jquery.dataTables.scroller.js"></script>
<script type="text/javascript" src="lib/jquery.form.js"></script>
<script type="text/javascript" src="lib/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="lib/jquery.minicolors.min.js"></script>
<script type="text/javascript" src="lib/jquery.switchButton.js"></script>
<script type="text/javascript" src="lib/jquery.ui.timepicker.js"></script>
<script type="text/javascript" src="lib/jquery.ui.widget.js"></script>
<script type="text/javascript" src="lib/jquery.validate.js"></script>
<script type="text/javascript" src="lib/moment.js"></script>
<script type="text/javascript" src="lib/select2.js"></script>
<script type="text/javascript" src="lib/bootstrap.js"></script>
<script type="text/javascript" src="lib/jquery.rating.pack.js"></script>
<script type="text/javascript" src="lib/jquery.MetaData.js"></script>
<script type="text/javascript" src="lib/jquery.rating.js"></script>